package it.polimi.ingsw.gc27.Enumerations;

public enum ObjectiveRequirementType {
    THREEPLANTKINGDOM,
    THREEANIMALKINGDOM,
    THREEINSECTKINGDOM,
    THREEFUNGIKINGDOM,
    BLUELADDER,
    REDLADDER,
    PURPLELADDER,
    GREENLADDER,
    DOUBLEQUILL,
    DOUBLEMANUSCRIPT,
    DOUBLEINKWELL,
    EACHDIFFERENTTYPE,
    TWOPLUSONEUPPERRIGHT,
    TWOPLUSONEUPPERLEFT,
    TWOPLUSONELOWERLEFT,
    TWOPLUSONELOWERRIGHT
}
