package it.polimi.ingsw.gc27.Enumerations;

public enum ObjectiveRequirementType {
    THREEPLANTKINGDOM,
    THREEANIMALKINGDOM,
    THREEINSECTKINGDOM,
    THREEFUNGIKINGDOM,
    LEFTLADDER,
    RIGHTLADDER,
    DOUBLEQUILL,
    DOUBLEMANUSCRIPT,
    DOUBLEINKWELL,
    EACHDIFFERENTTYPE,
    TWOPLUSONEUPPERRIGHT,
    TWOPLUSONEUPPERLEFT,
    TWOPLUSONELOWERLEFT,
    TWOPLUSONELOWERRIGHT
}
